### ISSUE TITLE
`##[error]File not found: '/home/runner/work/_actions/technote-space/auto-cancel-redundant-job/gh-actions/lib/main.js'`

### ISSUE THREAD

**Issue by mxcl** [technote-space/auto-cancel-redundant-job#35]
## Describe the bug: バグの概要

Running the action for the latest version (1.4.3) results in the error:

```
##[error]File not found: '/home/runner/work/_actions/technote-space/auto-cancel-redundant-job/gh-actions/lib/main.js'
```

## Operating environment: バグが発生した環境

`ubuntu_latest` activated for pull-request flows.

## Additional context: 補足

Dependabot submitted a PR for us to update from `@v1` to `@v1.4.3` and we get this error as part of the checks for that PR so I haven’t merged it. I notice that the CI for this project has the [same error](https://github.com/technote-space/auto-cancel-redundant-job/actions/runs/220567289).

**Comment by technote-space** [comment]
@mxcl 
I fixed this issue.
Thank you.
